dependencies:
  - requests
  - notebook
  - ipywidgets
  - matplotlib
  - seaborn
  - pandas
  - polars
  - pyarrow
  - black
  - geopandas
  - bs4
  - numpy
  - tqdm
  - pip
  - pip:
    - adbc_driver_manager

