```{r}
library(osmdata)
library(sf)
library(leaflet)
library(ggplot2)
library(dplyr)
library(tidyr)
library(terra)
library(RColorBrewer)
source("load.R")
bbox_terra <- ext(c(6, 18.5, 36, 48))
bbox_osm <- c(6, 36, 18.5, 48)
dem <- rast("temp/dem/dem1.tif")
```
```{r}
ita_shp <- read_sf("~/Local_Workspace/Datasets/geoBoundaries/ITA-ADM0/geoBoundaries-ITA-ADM0.geojson") |> st_cast("MULTIPOLYGON")
```

```{r}
# query <- "[out:json][timeout:40];
# (
#   nwr[\"name:it\"=\"Milano\"](45.07739974122637,8.684692382812502,45.722000899316875,10.030517578125002);
# );
# out geom;"

q <- opq(bbox = bbox_osm, timeout = 200) |>
    add_osm_features(list(
        "highway" = "motorway",
        # "highway" = "primary",
        "place" = "city"
    )) |>
    osmdata_sf()
ilines <- q$osm_lines |> select(name, highway, ref, int_ref, lanes, tunnel)
ipoints <- q$osm_points |>
    filter(place == "city") |>
    select(name, place, population)
write_sf(ilines, "temp/osm/ita_lines.geojson", append = FALSE)
write_sf(ipoints, "temp/osm/ita_points.geojson", append = FALSE)
```

```{r}
# q <- osmdata_sf(query)
```

```{r}
ilines <- read_sf("temp/osm/ita_lines.geojson") |> st_filter(ita_shp)
ipoints <- read_sf("temp/osm/ita_points.geojson") |> st_filter(ita_shp)
```

```{r}

```

```{r}
ggplot() +
    geom_sf(data = ilines, color = "turquoise") +
    geom_sf(data = ipoints |> drop_na(name) |> filter(place == "city"), color = "red") +
    geom_sf_label(data = ipoints |> drop_na(name) |> filter(place == "city"), aes(label = name), nudge_x = 0.01, nudge_y = -0.01)
```

```{r}
svg("ita.svg", height = 15, width = 11.5)
contour(dem, levels = c(50, 500, 1000, 1500), lwd = 0.2, drawlabels = FALSE, maxcells = 5000000, col = "gray50")
plot(ita_shp |> st_geometry(), color = "gray80", lwd = 0.8, add = TRUE)
plot(ilines |> group_by(ref) |> summarise(geometry = st_union(geometry)), add = TRUE)
plot(ipoints |> drop_na(name) |> filter(population > 200000) |> st_geometry(), add = TRUE, col = "red", pch = ".")
dev.off()
```

```{r}
plot(ita_shp |> st_geometry(), lwd = 0.4)
plot(ipoints |> drop_na(name) |> filter(population > 200000) |> st_geometry(), add = TRUE, col = "red", pch = ".")
```