---
title: "Pairing stations"
author: "Davide Nicoli"
date: "`r Sys.Date()`"
output: html_document
---

# Comportamento delle reti di stazioni
```{r common-includes, echo = FALSE, warning = FALSE, message = FALSE}
source("load.R")
source("load_utils.R")
source("plot_helpers.R")
library(arrow)
library(tibble)
library(dplyr)
library(ggplot2)
library(sf)
library(rlang)
library(zeallot)
temp <- "temp/pairing"
use_cache <- TRUE
```

```{r funcs-defs, echo = FALSE, warning = FALSE, message = FALSE}
# Matching/loading functions. Watch out for the start date!
build_matches <- function(db1, db2) {
    st_join(
        db1,
        db2, st_is_within_distance,
        dist = units::set_units(10, "m"), suffix = c(".x", ".y"), left = FALSE
    ) |> st_drop_geometry()
}

to_series <- function(metadata_matches, series1, series2, tvar) {
    # Transform a dataframe of matches into a dataframe of series
    ids1 <- metadata_matches |>
        pull(identifier.x) |>
        unique()
    series1 <- series1 |>
        as_tibble() |>
        drop_na() |>
        filter(identifier %in% ids1) |>
        rename(T = {{ tvar }})

    ids2 <- metadata_matches |>
        pull(identifier.y) |>
        unique()
    series2 <- series2 |>
        as_tibble() |>
        drop_na() |>
        filter(identifier %in% ids2) |>
        rename(T = {{ tvar }})

    series1 |>
        left_join(
            metadata_matches,
            join_by(identifier == identifier.x),
            # Ci sono casi in cui più stazioni SCIA sono associate alla stessa stazione DPC e viceversa, per esempio quando una stazione viene spostata.
            relationship = "many-to-many"
        ) |>
        inner_join(
            series2,
            join_by(identifier.y == identifier, date),
            relationship = "many-to-one"
        )
}

diff_series <- function(db1, db2, series1, series2, tvar, desc = NULL) {
    matches <- build_matches(db1, db2)
    matched_series <- cached_data(
        "JOIN",
        tvar,
        otherwise = function(db, tvar) {
            matches |>
                to_series(series1, series2, tvar) |>
                mutate(diff = T.x - T.y)
        },
        file.path("cache", "intermediates", "series"),
        suffix = desc,
        load_cache = use_cache & !is.null(desc)
    )
    list(metadata = matches, data = matched_series)
}

plot_hist_net <- function(data, diff_var) {
    ggplot(data = data |> filter(abs({{ diff_var }}) <= 1.05)) +
        geom_histogram(
            aes({{ diff_var }}),
            binwidth = 0.1,
            bins = 21,
            center = 0
        )
}

these_plots <- function(m.db1, m.db2, s.db1, s.db2, tvar, diff_tag, desc) {
    diffs <- diff_series(
        m.db1,
        m.db2,
        s.db1 |> filter(date >= "2010-01-01"),
        s.db2 |> filter(date >= "2010-01-01"),
        tvar,
        desc = desc
    )
    p_net <- plot_hist_net(diffs$data, diff) +
        facet_wrap(. ~ rete, ncol = 3, scales = "free_y") +
        labs(title = tvar, x = diff_tag)
    ggsave(str_glue("plots/hist_net_{diff_tag}_{tvar}.pdf"), p_net, width = 9, height = 12)
    p_state <- plot_hist_net(diffs$data, diff) +
        facet_wrap(. ~ state.x, ncol = 3, scales = "free_y") +
        labs(title = tvar, x = diff_tag)
    ggsave(str_glue("plots/hist_state_{diff_tag}_{tvar}.pdf"), p_state, width = 9, height = 18)
    list(diffs$data, p_net, p_state)
}
m.scia.tmax <- retrieve.metadata("SCIA", "T_MAX")
s.scia.tmax <- retrieve.series("SCIA", "T_MAX") |> filter(date >= as.Date("2010-01-01"))
m.scia.tmin <- retrieve.metadata("SCIA", "T_MIN")
s.scia.tmin <- retrieve.series("SCIA", "T_MIN") |> filter(date >= as.Date("2010-01-01"))
gc()
```

## T_MAX DPC
```{r tmax-matches, fig.height = 8}
tvar <- "T_MAX"
c(d.tmax, p_net, p_state) %<-% these_plots(
    m.scia.tmax,
    retrieve.metadata("DPC", tvar),
    s.scia.tmax,
    retrieve.series("DPC", tvar) |> filter(date > as.Date("2010-01-01")),
    tvar,
    "SCIA-DPC",
    "_SCIA-DPC_2010"
)
p_net
p_state
```

## T_MIN
```{r tmin-matches, fig.height = 8}
tvar <- "T_MIN"
c(d.tmin, p_net, p_state) %<-% these_plots(
    m.scia.tmin,
    retrieve.metadata("DPC", tvar),
    s.scia.tmin,
    retrieve.series("DPC", tvar) |> filter(date > as.Date("2010-01-01")),
    tvar,
    "SCIA-DPC",
    "_SCIA-DPC_2010"
)
p_net
p_state
```

## Ts
```{r fullt-matches}
data <- bind_rows(
    T_MAX = d.tmax |> select(diff, elevation.x),
    T_MIN = d.tmin |> select(diff, elevation.x),
    .id = "tvar"
)
ggplot(data = data |> filter(abs(diff) <= 1.05)) +
    geom_histogram(
        aes(diff, fill = tvar),
        bins = 21,
        binwidth = 0.1,
        center = 0,
        position = "dodge",
    ) +
    labs(x = "SCIA-DPC")
ggsave(str_glue("plots/hist_net_both.pdf"), width = 12, height = 12)
```

## T_MAX NODPC
```{r tmax-matches-nodpc, fig.height = 8}
tvar <- "T_MAX"
m.brun <- retrieve.metadata("BRUN", tvar)
m.dpc <- retrieve.metadata("DPC", tvar)
m.nodpc <- anti_join(m.brun, m.dpc |> st_drop_geometry(), by = "identifier")
s.nodpc <- retrieve.series("BRUN", tvar) |> filter(identifier %in% m.nodpc$identifier, date > as.Date("2010-01-01"))
c(d.tmax, p_net, p_state) %<-% these_plots(
    m.scia.tmax,
    m.nodpc,
    s.scia.tmax,
    s.nodpc,
    tvar,
    "SCIA-NODPC",
    "_SCIA-NODPC_2010"
)
p_net
p_state
gc()
```

## T_MIN NODPC
```{r tmin-matches-nodpc, fig.height = 8}
tvar <- "T_MIN"
m.brun <- retrieve.metadata("BRUN", tvar)
m.dpc <- retrieve.metadata("DPC", tvar)
m.nodpc <- anti_join(m.brun, m.dpc |> st_drop_geometry(), by = "identifier")
s.nodpc <- retrieve.series("BRUN", tvar) |> filter(identifier %in% m.nodpc$identifier, date > as.Date("2010-01-01"))
c(d.tmin, p_net, p_state) %<-% these_plots(
    m.scia.tmin,
    m.nodpc,
    s.scia.tmin,
    s.nodpc,
    tvar,
    "SCIA-NODPC",
    "_SCIA-NODPC_2010"
)
p_net
p_state
gc()
```

Anche le stazioni non DPC presentano differenze più o meno consistenti e sistematiche con SCIA, a seconda della rete.

## Ts
```{r fullt-matches-nodpc}
data <- bind_rows(
    T_MAX = d.tmax |> select(diff, elevation.x),
    T_MIN = d.tmin |> select(diff, elevation.x),
    .id = "tvar"
)
ggplot(data = data |> filter(abs(diff) <= 1.05)) +
    geom_histogram(
        aes(diff, fill = tvar),
        bins = 21,
        binwidth = 0.1,
        center = 0,
        position = "dodge",
    ) +
    labs(x = "SCIA-NODPC")
ggsave(str_glue("plots/hist_net_NODPC_both.pdf"), width = 12, height = 12)
```

```{r, fig.height=12, fig.width=9}
ggplot(data = build_matches(m.scia.tmin, m.nodpc)) +
    geom_bar(aes(rete, fill = state.x)) +
    guides(x = guide_axis(angle = 90))
```
