---
title: ""
author: "Davide Nicoli"
date: "2025-03-24"
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
    includes:
      in_header: "preamble.tex"
  html_document:
    df_print: paged
bibliography: rbiblio.bib
---

## Introduzione
Il lavoro ha avuto l'obiettivo di elaborare un dataset degli estremi minimi e massimi giornalieri di temperatura relativi al trentennio 1991-2020 per le serie registrate nel centro-nord italia, nell'ambito di un più ampio progetto volto alla costruzione di un dataset ad alta risoluzione delle normali climatologiche esteso all'intero territorio italiano. In particolare si mira ad aggiornare il lavoro svolto in @brunettiHighresolutionTemperatureClimatology2014.

Il dataset risultante è stato costruito attraverso la raccolta, il controllo e l'integrazione di dati ed anagrafiche di stazione provenienti da diverse fonti provinciali, regionali e nazionali.

Dopo aver finalizzato la raccolta si è proceduto ad una valutazione di massima della capacità del modello elaborato nel lavoro precedente di interpolare le climatologie del nuovo dataset.

## Metodologia
1. Raccolta dei dati: sono stati acquisiti dati da vari enti, tra cui ARPA, ISPRA, ISAC-CNR e Dipartimento di Protezione Civile, prestando particolare attenzione a coprire il periodo 1991-2020 e recuperando i dati rimanenti dove farlo non fosse troppo dispendioso in termini di tempo. La frammentazione e l'eterogeneità delle fonti hanno richiesto un attento lavoro di standardizzazione di dati e anagrafiche;
2. Merging: le serie di dati sono state integrate attraverso un processo che ha combinato fonti diverse per garantire una maggiore copertura spaziale e temporale ed eliminare le serie duplicate;
3. Controllo qualità: è stata eseguita un'analisi dei dati e metadati delle serie per individuare errori e incongruenze. In particolare, per ogni serie di dati si è fatto un confronto con la rianalisi ERA5 e con le serie meteorologiche limitrofe tramite tecniche studiate in altri lavori [@mitchellImprovedMethodConstructing2005; @diluzioConstructingRetrospectiveGridded2008]; per i metadati invece si è fatto un controllo manuale nei casi sospetti;
4.Valutazione del modello di interpolazione: ogni serie del dataset soddisfacente determinati criteri di qualità minimi e completata dei dati mancanti è stata confrontata con la corrispondente serie sintetica ricostruita tramite interpolazione geospaziale delle serie limitrofe con Local Weighted Linear Regression.

## Risultati
- Il dataset finale comprende 2501 serie sul territorio del centro-nord Italia, più 1294 nelle zone limitrofe dell'arco alpino;
- è stata riscontrata una discrepanza maggiore tra modello ed osservazioni nelle temperature minime rispetto alle massime, particolarmente evidente in aree montane e costiere, in determinate regioni più che in altre;
- l'analisi ha evidenziato la necessità di studiare in maniera più approfondita la procedura di interpolazione spaziale dei dati aggiungendo al modello ulteriori algoritmi per meglio catturare il legame tra le caratteristiche geografiche del territorio e le normali climatiche.

## Conclusioni
L'integrazione delle diverse fonti ha permesso di ottenere un dataset con disponibilità di dati molto maggiore di quelli preesistenti per lo studio del clima italiano. Tuttavia, permangono alcune criticità, come la difficoltà di omogeneizzare dati provenienti da strumenti e metodologie differenti.