---
title: Elaborazione di un dataset degli estremi di temperatura mensili per il territorio italiano
author: Davide Nicoli
output: pdf_document
# bibliography: rbiblio.bib
---
## Introduzione
Il lavoro ha avuto l'obiettivo di elaborare un dataset delle normali climatologiche mensili relative al trentennio 1991-2020 delle temperatura minime e massime giornaliere per le serie registrate nel centro-nord italia, nell'ambito di un più ampio progetto volto alla costruzione di un dataset ad alta risoluzione esteso all'intero territorio italiano. In particolare si cerca di aggiornare

Il dataset risultante è stato costruito attraverso la raccolta, il controllo e l'integrazione di dati provenienti da diverse fonti provinciali, regionali e nazionali.

## Metodologia
1. Raccolta dei dati: sono stati acquisiti dati da vari enti, tra cui ARPA, SCIA (dataset ISPRA), CNR-ISAC e il dataset del Dipartimento di Protezione Civile, prestando particolare attenzione a coprire il periodo 1991-2020. La frammentazione e l'eterogeneità delle fonti hanno richiesto un attento lavoro di standardizzazione;
2. Merging: le serie di dati sono state integrate attraverso un processo che ha combinato fonti diverse per garantire una maggiore copertura spaziale e temporale ed eliminare le serie duplicate;
3. Controllo qualità: è stata eseguita un'analisi dei dati per individuare errori e incongruenze, utilizzando confronti con la rianalisi ERA5 e con stazioni meteorologiche limitrofe tramite tecniche appositamente studiate in altri lavori;
4. Stima delle normali climatiche: sono state calcolate medie climatologiche mensili, considerando solo le serie con almeno cinque anni di dati validi e completando quelle con un numero non troppo elevato di dati mancanti.

## Risultati
- Il dataset finale comprende 2508 serie, con un miglioramento significativo rispetto alle fonti originali in termini di continuità e accuratezza.
- È stata riscontrata una discrepanza maggiore nelle temperature minime rispetto alle massime, particolarmente evidente in aree montane e costiere.
- L’analisi ha evidenziato la necessità di ulteriori miglioramenti nel trattamento dei dati di regioni con orografia complessa.

## Conclusioni
L’integrazione delle diverse fonti ha permesso di ottenere un dataset più completo e affidabile per lo studio del clima italiano. Tuttavia, permangono alcune criticità, come la difficoltà di omogeneizzare dati provenienti da strumenti e metodologie differenti. Il lavoro rappresenta un passo avanti nella disponibilità di dati climatologici per analisi ambientali e previsioni a lungo termine.