---
title: "Stima delle normali di stazione"
---

Scopo di questa parte del lavoro è, partendo da serie di dati di stazione grezzi o già aggregati a livello giornaliero o mensile, produrre le normali climatologiche mensili georiferite sulle stazioni di rilevazione, ovvero medie delle temperature massime e minime giornaliere per ogni mese dell'anno collocate nello spazio. Il dataset risultante pertanto consterà di due tabelle: quella dei metadati di ogni serie (almeno latitudine, longitudine, quota, identificativo della serie) e quella dei contenuti delle serie (mese a cui la stima si riferisce, identificativo della serie di appartenenza, valori di temperatura minima e massima in $\mathrm{°C}$.

Il procedimento, in linea con le linee guida WMO[@WMOGuidelinesNormalsCalculation2017], consta di quattro passaggi:

1.  raccolta dei dati: trasformazione dei dati come forniti dai gestori delle reti di misura in serie giornaliere di estremi di temperatura;
2.  controllo qualità: eliminazione degli errori presenti nelle serie giornaliere tramite analisi puntuale dei dati e confronto con dati limitrofi;
3.  omogeneizzazione: individuazione e correzione delle deviazioni che il cambiamento di strumentazione o ambiente circostante introducono nelle serie;
4.  aggregazione su scala mensile.

{{< include /elaborato/sezioni/stima_normali/raccolta_dati.qmd >}}

## SCIA

```{r}
#| label: fig-sciadisp
#| fig-cap: "Disponibilità di serie SCIA mese per mese. Sono rappresentate solo le serie che riportano almeno 25 misure per mese."
#| cache: true

library(DBI, warn.conflicts = F, quietly = T)
library(duckdb, warn.conflicts = F, quietly = T)
library(zeallot, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(lubridate, warn.conflicts = F, quietly = T)
source("src/database/query/data.R")
source("notebooks/ds_regionali/procedure/common_steps.R")

conn <- dbConnect(duckdb())
stations <- query_checkpoint_meta("SCIA", "raw", conn) |> filter(lat > 42.2, !(district %in% c("Lazio", "Abruzzo")), country == "Italy") |> select(sensor_key, district)
p <- query_checkpoint_data("SCIA", "raw", conn) |>
  filter(between(year(date), 1991L, 2020L), variable == 1L) |>
  semi_join(stations, by = "sensor_key") |>
  monthly_availabilities(minimum_valid_days = 25L) |>
  ungroup() |>
  filter(qc_month_available) |>
  left_join(stations, by = "sensor_key") |>
  count(district, year, month) |>
  collect() |>
  mutate(m = make_yearmonth(year, month), .keep = "unused") |>
  as_tsibble(key = district, index = m) |>
  ggplot(mapping = aes(x = m, y = n)) + geom_line()
    
p +
  labs(x = "Mese", y = "n", title = "Disponibilità di serie SCIA") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45)) +
  facet_wrap(vars(district), ncol = 4L)
```
